### ISSUE TITLE
Pathway download in different formats (word, pdf, protege) not working

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/testing-issues#23]
download options not working:
https://plantreactomedev.oicr.on.ca/PathwayBrowser/#/R-OSA-1119434&SEL=R-OSA-9639018&PATH=R-OSA-2744345,R-OSA-2744344,R-OSA-9640027&DTAB=DT&ANALYSIS=MjAxOTA0MjQxNDUxMjNfMTE%253D&RESOURCE=UNIPROT

**Comment by elserj** [comment]
Fixed for word and pdf by adding "Alias" line for /img-tmp to apache conf file.  Protege export still not working for some other reason.  Doesn't generate the tarball.  Still working on.

**Comment by preecej** [comment]
Protege now working.
