### ISSUE TITLE
no expression of Al stress pathway genes 

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/testing-issues#24]
showing error msg for:
ASR1, ASR5, ART1, and WRKY22 expression

https://plantreactomedev.oicr.on.ca/PathwayBrowser/#/R-OSA-9639136&SEL=R-OSA-9639205&PATH=R-OSA-8932729,R-OSA-9618278&DTAB=EX

**Comment by preecej** [comment]
folding this into #17
