### ISSUE TITLE
"ABA mediated signaling" Pathway at two locations

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/testing-issues#27]
"ABA mediated signaling" Pathway shows up as a child pathway under "Response to Salinity" in event hierarchy; however, it is already in hormone signaling, transport and metabolism. 

 
<img width="431" alt="Screenshot 2019-10-29 14 58 37" src="https://user-images.githubusercontent.com/14987545/67804360-c45ee780-fa5c-11e9-84f5-469b7605eac8.png">

<img width="424" alt="Screenshot 2019-10-29 14 58 57" src="https://user-images.githubusercontent.com/14987545/67804370-caed5f00-fa5c-11e9-8bf7-0ceec3971d16.png">

**Comment by preecej** [comment]
By design. It is not counted twice.
