### ISSUE TITLE
connecting arrow missing between G1 phase & G1/S transition 

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/testing-issues#31]
In Mitosis diagram, a connecting arrow between G1 phase & G1/S transition is missing. However, preceding event in "G1/S transition" is "G1 phase" under pathway description panel. Diagram pic attached for reference.

![R-OSA-9640713](https://user-images.githubusercontent.com/14987545/87824199-708a6d80-c83a-11ea-9e9a-1b770f62d993.png)

**Comment by elserj** [comment]
Fixed by @deustp01 via email convo on 2/20/23.

For now, it looks like when we find these, to just identify them to Peter and he can fix in gk_central.
